import Head from 'next/head'
import Nav from '@/components/nav'
import Hero from '@/components/hero'
import Features from '@/components/features'
import About from '@/components/about'
import Services from '@/components/services'
import Footer from '@/components/footer'

export default function Home() {
  return (
    <>
      <Head>
        <title>Digital App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Nav/>
      <Hero/>
      <Features/>
      <About/>
      <Services/>
      <Footer/>
    </>
  )
}
